### ISSUE TITLE
Custom commands are not working properly

### ISSUE THREAD

**Issue by TS-Steve** [aMytho/GlimBoi#91] opened 2021-09-07 18:15 UTC
Using custom commands in chat does not return the data assigned. Instead, when a custom command is used, nothing happens. I'm using the latest version.

I have tried default commands which work fine but the custom commands are not returning anything.

![Rocket League](https://user-images.githubusercontent.com/78236565/132391834-805c7053-7328-407f-b104-7ad2a260a684.png)

**Comment by aMytho** [comment] 2021-09-07 20:35
Thanks for making an issue!

The problem is likely one of a few things:

1. The command response contains links and the channel has them disabled.
2. The command is more than 1 word. (IDK if this is works, but its unlikely)
3. The command is invalid in some form.

Can you post an image of your command page?

**Comment by TS-Steve** [comment] 2021-09-08 07:09
You're right, I had links disabled but I thought mods were allowed to bypass that including bots.

**Comment by TS-Steve** [comment] 2021-09-08 07:20
I'm wondering if there is a way to make links clickable or is that not coded into the bot right now.

**Comment by MythoAway** [comment] 2021-09-08 14:17
Responding from alt account-

Glimesh has that as a channel setting for Glimesh chat. It would be possible to implement that into the bot chat, I just need to find a way to parse it with JS. After that I can direct it to the users default browser (can't load the link in the bot, electron security reasons). I also want to add the glimdrops and channel emotes, so I'll likely get to this eventually (after/during v2.0). That being said, most users just use Glimesh chat and let the bot run in minimized mode so this isn't a priority atm.

**Comment by aMytho** [comment] 2021-09-09 00:39
I forgot about the chat parts API. Parsing is already handled, just have to switch the chat system.

**Comment by TS-Steve** [comment] 2021-09-09 00:54
> Responding from alt account-
> 
> Glimesh has that as a channel setting for Glimesh chat. It would be possible to implement that into the bot chat, I just need to find a way to parse it with JS. After that I can direct it to the users default browser (can't load the link in the bot, electron security reasons). I also want to add the glimdrops and channel emotes, so I'll likely get to this eventually (after/during v2.0). That being said, most users just use Glimesh chat and let the bot run in minimized mode so this isn't a priority atm.

Gotcha, can't wait for Glimdrops and channel emotes to be added.

> I forgot about the chat parts API. Parsing is already handled, just have to switch the chat system.

Ah I see.

**Comment by aMytho** [comment] 2021-11-01 20:39
Added in 2.0, will be released when I know the final test version is without errors.

**Closed by aMytho** 2021-11-01 20:39 UTC
